ci: Disable smoke test

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -103,27 +103,27 @@ jobs:
           builder: ${{ steps.buildx.outputs.name }}
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: type=local,dest=/tmp/.buildx-cache
-      - name: Start Streamr Docker Stack
-        uses: streamr-dev/streamr-docker-dev-action@v1.0.0-alpha.3
-        with:
-          services-to-start: "core-api nginx ethereum-watcher"
-      - name: Run Smoke test
-        run: |
-          wait_time=10;
-          for (( i=0; i < 5; i=i+1 )); do
-            docker logs streamr-dev-ethereum-watcher > out.txt
-            grep -q "Connected to Ethereum network" out.txt
-            res=$?
-            if test "$res" != "0"; then
-              echo "Attempting to connect to Ethereum-Watcher retrying in $wait_time seconds"
-              sleep $wait_time
-              wait_time=$(( 2*wait_time ))
-            else
-              break
-            fi
-          done
-          set -e
-          grep -q "Connected to Ethereum network" out.txt
+#      - name: Start Streamr Docker Stack
+#        uses: streamr-dev/streamr-docker-dev-action@v1.0.0-alpha.3
+#        with:
+#          services-to-start: "core-api nginx ethereum-watcher"
+#      - name: Run Smoke test
+#        run: |
+#          wait_time=10;
+#          for (( i=0; i < 5; i=i+1 )); do
+#            docker logs streamr-dev-ethereum-watcher > out.txt
+#            grep -q "Connected to Ethereum network" out.txt
+#            res=$?
+#            if test "$res" != "0"; then
+#              echo "Attempting to connect to Ethereum-Watcher retrying in $wait_time seconds"
+#              sleep $wait_time
+#              wait_time=$(( 2*wait_time ))
+#            else
+#              break
+#            fi
+#          done
+#          set -e
+#          grep -q "Connected to Ethereum network" out.txt
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v1.10.0
         with:
